### ISSUE TITLE
turn right and left not working on android

### ISSUE THREAD

**Issue by brahimjid** [osamaqarem/liveness-detection-react-native#2]

**Comment by vinhhoangdo** [comment]
You can follow this link and try converting yaw and roll.!!!
Work for me: ` angle > 180 ? angle - 360 : angle`
https://stackoverflow.com/questions/67555851/expo-face-detector-angle

**Comment by osamaqarem** [comment]
Duplicate of https://github.com/osamaqarem/liveness-detection-react-native/issues/1
